{"success": false, "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/falcon_analyzer-0.2.28-py3.10.egg/falcon/__main__.py\", line 835, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/usr/local/lib/python3.10/dist-packages/falcon_analyzer-0.2.28-py3.10.egg/falcon/__main__.py\", line 87, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/home/im/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py\", line 722, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/home/im/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py\", line 211, in __init__\n    self._compile(**kwargs)\n  File \"/home/im/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py\", line 633, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/home/im/.local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py\", line 86, in compile\n    hardhat_like_parsing(crytic_compile, self._target, build_directory, self._target)\n  File \"/home/im/.local/lib/python3.10/site-packages/crytic_compile/platform/hardhat.py\", line 52, in hardhat_like_parsing\n    raise InvalidCompilation(txt)\ncrytic_compile.platform.exceptions.InvalidCompilation: Compilation failed. Can you run build command?\nout/build-info is not a directory.\n", "results": {}, "engine_version": "0.2.28"}